### ISSUE TITLE
Branch to Practice Issue syste

### ISSUE THREAD

**Issue by drakamaleon** [tahtty/Mockito-2.0#1]
In **Software Engineering**  class, we have to create a new branc to practice the issue management. And practice the 10 steps of  *Maintenance*

**Comment by tahtty** [comment]
Para este tipo de issue no es necesario reproducir el problema, no hay problema que reproducir

**Comment by tahtty** [comment]
@lubevica va a encargarse de este issue

**Comment by lubevica** [comment]
Esto no tiene impacto directo sobre el proyecto, para el día de hoy antes de la 13:30 estará creada la nueva branch. @drakamaleon

**Comment by lubevica** [comment]
La rama ha sido creada con el nombre Issues para los fines pertinentes. @drakamaleon

**Comment by lubevica** [comment]
Este issue no necesita de pruebas de integración ni documentación ya que no afecta al código.

**Comment by lubevica** [comment]
@drakamaleon el branch solicitado fue creado, verificar si el problema presentado ha sido resuelto con esta solución propuesta.

**Comment by drakamaleon** [comment]
Muchas gracias @lubevica, el trabajo realizado es lo que necesitaba que se hiciera.

**Comment by lubevica** [comment]
@tahtty las pruebas de aceptacion han sido aceptadas por el cliente. EL problema ha sido solucionado.

**Comment by tahtty** [comment]
Dado que todas las actividades de este issue han sido completadas se da por terminado el issue y etaremos al tanto de cualquier nueva incidencia/issue

**Comment by tahtty** [comment]
Dado que todas las actividades de este issue han sido completadas se da por terminado el issue y etaremos al tanto de cualquier nueva incidencia/issue
