### ISSUE TITLE
Nueva funcionalidad requerida

### ISSUE THREAD

**Issue by cmonsalvec** [tahtty/Mockito-2.0#2]
Nuestros usuarios están muy contentos con lo que han desarrollado, pero es necesario ampliar la funcionalidad a una división. La división debe ser implementada en base a restas y sumas. Las sumas para contar el número de repeticiones, las restas para ir restando sucesivamente del dividendo el divisor. Por ejemplo, si deseo dividir 7 para 2, entonces hago 7-2=5, 5-2=3, 3-2=1, y como 1 es menor a 2 me detengo. Como tuve 3 repeticiones, entonces la respuesta es 3, y el residuo es 1. 

Por cuestiones de responsabilidad, se desea que al menos dos personas se encarguen de la codificación, uno para modificar el menú de operaciones (interacción con usuario), y otro para implementar la operación.

Por cuestiones de calidad se quiere que el que haga las pruebas finales no debe haber codificado.

Por lo tanto, requerimos se evidencie el buen trato de este incidente en Github, el desarrollo en un nuevo branch de este requerimiento por parte de dos desarrolladores, y que se muestren las pruebas ejecutadas por otro miembro del equipo.

**Comment by tahtty** [comment]
Estimado PhD. @cmonsalvec , hemos revisado las condiciones de los requerimientos del ticket que ha puesto, y efectivamente esa funcionalidad que pide no se encuentra actualmente en el programa.

**Comment by tahtty** [comment]
Para el siiguiente incidente, van a trabajar 2 miembros del equipo en el desarrollo y 1 en pruebas:
@lubevica se encargará del desarrollo de la instancia de División y la interface OperacionDivision para que Juan pueda trabajarlo en el frontend
@jealvarado se encargará de la interface con el usuario (frontend), modificar el menú y lo que sea necesario para que el usuario pueda acceder a esta funcionalidad
@drakamaleon se encargará de las pruebas requeridas para lo desarrollado por los anteriores miembros mencionados
Proceder a analizar el impacto del incidente y desarrollo respectivo. Mantenerme informada de toda actualización o avance del trabajo

**Comment by jealvarado** [comment]
El issue que se ha presentado no es incompatible con el proyecto actual, pudiendo integrarse completamente en el proyecto al no existir inconsistencias con la funcionalidad actual

**Comment by lubevica** [comment]
Para la parte de la division tampoco genera ningún inconveniente ni incompatibilidad con el trabajo que se ha realizado. se va a proceder a crear una nueva rama para comenzar con la implementación

**Comment by lubevica** [comment]
Se ha procedido a realziar la implementación de la división

**Comment by jealvarado** [comment]
Completada la implementación del FrontEnd con la nueva funcionalidad

**Comment by drakamaleon** [comment]
Pruebas de integración realizadas con éxito

**Comment by tahtty** [comment]
He revisado lo realizado y codificado. Y se ha llevado a cabo lo necesario. Ahora me dispongo a solicitar las pruebas de aceptación. Gracias @drakamaleon @jealvarado @lubevica

**Comment by tahtty** [comment]
Estimado @cmonsalvec , puede proceder a revisar y, de ser el caso, aceptar la solución desarrollada que se encuentra en la rama Division. Saludos

**Comment by cmonsalvec** [comment]
Muchas gracias Tahís, sería bueno que me enviaran un link donde pueda ver el resultado realizado. Además, veo que han pasado las pruebas de aceptación, pero realmente nadie del equipo técnico me ha hecho la demostración del nuevo requerimiento funcionando. Recomiendo que realicen sus análisis de impacto de manera más profunda: recursos que serán necesarios, cambios que se perciben se deben realizar, tiempos estimados para el trabajo, etc.
